/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EVnMtQzNao1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuLabel } from "@/components/ui/dropdown-menu"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function MoviesPage() {
  const [isDarkMode, setIsDarkMode] = useState(false)
  return (
    <div className={`flex flex-col w-full min-h-screen ${isDarkMode ? "dark" : ""}`}>
      <header className="h-14 flex items-center justify-between px-6 bg-primary text-primary-foreground">
        <div className="flex items-center gap-4">
          <FilmIcon className="w-6 h-6" />
          <h1 className="text-xl font-bold">Movie Magic</h1>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Movies
            </Link>
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Watchlist
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => setIsDarkMode(!isDarkMode)}>
            {isDarkMode ? <SunIcon className="w-5 h-5" /> : <MoonIcon className="w-5 h-5" />}
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JP</AvatarFallback>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem>My Account</DropdownMenuItem>
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex items-center gap-4 bg-primary py-4 px-6">
        <div className="relative flex-1">
          <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-primary-foreground" />
          <Input
            type="search"
            placeholder="Search movies..."
            className="pl-8 w-full bg-primary-foreground/10 rounded-md text-primary-foreground"
          />
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" className="w-40">
              Categories
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>Categories</DropdownMenuLabel>
            <DropdownMenuItem>Action</DropdownMenuItem>
            <DropdownMenuItem>Comedy</DropdownMenuItem>
            <DropdownMenuItem>Drama</DropdownMenuItem>
            <DropdownMenuItem>Horror</DropdownMenuItem>
            <DropdownMenuItem>Sci-Fi</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" className="w-40">
              Certification
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>Certification</DropdownMenuLabel>
            <DropdownMenuItem>G</DropdownMenuItem>
            <DropdownMenuItem>PG</DropdownMenuItem>
            <DropdownMenuItem>PG-13</DropdownMenuItem>
            <DropdownMenuItem>R</DropdownMenuItem>
            <DropdownMenuItem>NC-17</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
      <div className="flex-1 overflow-auto grid gap-8">
        <div className="flex items-center gap-4 bg-card p-4 rounded-lg h-16">
          <img src="/placeholder.svg" alt="Movie Poster" width={96} height={144} className="rounded-lg" />
          <div className="flex-1 grid gap-2">
            <h2 className="text-xl font-bold">The Shawshank Redemption</h2>
            <Button variant="ghost" size="icon" className="ml-auto">
              <PlusIcon className="w-6 h-6" />
            </Button>
          </div>
        </div>
        <div className="flex items-center gap-4 bg-card p-4 rounded-lg h-16">
          <img src="/placeholder.svg" alt="Movie Poster" width={96} height={144} className="rounded-lg" />
          <div className="flex-1 grid gap-2">
            <h2 className="text-xl font-bold">The Godfather</h2>
            <Button variant="ghost" size="icon" className="ml-auto">
              <PlusIcon className="w-6 h-6" />
            </Button>
          </div>
        </div>
        <div className="flex items-center gap-4 bg-card p-4 rounded-lg h-16">
          <img src="/placeholder.svg" alt="Movie Poster" width={96} height={144} className="rounded-lg" />
          <div className="flex-1 grid gap-2">
            <h2 className="text-xl font-bold">The Dark Knight</h2>
            <Button variant="ghost" size="icon" className="ml-auto">
              <PlusIcon className="w-6 h-6" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function FilmIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>
  )
}


function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
